// <auto-generated />
// Generated by scripts/generate-rts-bindings.mjs from Aetheria C# MessagePack documents.

import { CultMesh } from "cultmesh-ts";
import type { CultMeshLiveFeedDiagnostic, CultMeshOperationContext, CultMeshOperationReceipt, CultMeshProjectionSource, CultMeshQueryContext, CultMeshQuerySurfaceDiagnostic, CultMeshQueryWatcher, CultMeshRouteHint, CultMeshSurfaceCatalogDiagnostic, CultMeshSurfaceCatalogIndexDiagnostic, CultMeshUnsubscribe, CultMeshVerseContext, CultMeshViewportRequest } from "cultmesh-ts";
import type { IpcMain } from "electron";

export const AetheriaRtsSchemas = {
  daemonCommand: "gamecult.aetheria.daemon_command.v1",
  eveCommand: "gamecult.eve.command.v1",
  daemonFrame: "gamecult.aetheria.daemon_frame.v1",
  daemonHealth: "gamecult.aetheria.daemon_health.v1",
  rtsViewport: "gamecult.aetheria.rts_viewport.v1",
  objectsViewport: "gamecult.aetheria.objects_viewport.v1",
  gravityViewport: "gamecult.aetheria.gravity_viewport.v1",
  currentZone: "gamecult.aetheria.current_zone.v1",
  currentEntity: "gamecult.aetheria.current_entity.v1",
  currentDocking: "gamecult.aetheria.current_docking.v1",
  stationRefit: "gamecult.aetheria.station_refit.v1",
  sectorMap: "gamecult.aetheria.sector_map.v1",
  zoneRender: "gamecult.aetheria.zone_render.v1",
  selectedObject: "gamecult.aetheria.selected_object.v1",
  inventory: "gamecult.aetheria.inventory.v1",
  starbridgeScenario: "gamecult.aetheria.starbridge_scenario.v1",
  starbridgeSession: "gamecult.aetheria.starbridge_session.v1",
  starbridgeSessionSummary: "gamecult.aetheria.starbridge_session_summary.v1",
  verseAuthorityPolicy: "gamecult.aetheria.verse_authority_policy.v1",
  authorityLease: "gamecult.aetheria.authority_lease.v1",
} as const;

export const AetheriaRuntimeDaemonCommandKinds = {
  none: 0,
  ping: 1,
  setTarget: 2,
  clearTarget: 3,
  targetNearest: 4,
  targetNext: 5,
  targetPrevious: 6,
  targetReticle: 7,
  setMoveVector: 8,
  setLookDirection: 9,
  setTractorPower: 10,
  fireWeaponGroup: 11,
  setWeaponGroupActive: 12,
  setWeaponGroupMembership: 13,
  setBehaviorActive: 14,
  activateConsumable: 15,
  sensorPing: 16,
  setItemEnabled: 17,
  setItemOverrideShutdown: 18,
  setThermotoggleTargetTemperature: 19,
  pickUpLoot: 20,
  restoreLoadout: 21,
  dock: 22,
  dockNearest: 23,
  undock: 24,
  interact: 25,
  setDockedCurrentShip: 26,
  towToStation: 27,
  enterWormhole: 28,
  tradePurchase: 29,
  transferCargoItem: 30,
  equipItem: 31,
  storeItem: 32,
  toggleHullConductivity: 33,
  setEntityName: 34,
  destroyEntity: 35,
  setOverrideShutdown: 36,
  setHeatsinksEnabled: 37,
  setShutdownPerformance: 38,
  toggleShieldEnabled: 39,
} as const;

export const AetheriaRuntimeEveCommandKinds = {
  unknown: 0,
  catalogRefresh: 1,
  operationsRefresh: 2,
  playerSettingsRefresh: 3,
  setPlayerName: 4,
  cycleTemperatureUnit: 5,
  decrementSignificantDigits: 6,
  incrementSignificantDigits: 7,
  cycleNebulaQuality: 8,
  toggleShowAsteroidsInMinimap: 9,
  inputSettingsRefresh: 10,
  beginInputCapture: 11,
  cancelInputCapture: 12,
  setBindingOverride: 13,
  toggleActionBar: 14,
  setActionBarEnabled: 15,
  saveLoadoutTemplate: 16,
  verseHostRefresh: 17,
  cycleVerseHostVisibility: 18,
  tradeValuePolicyRefresh: 19,
  setTradeValueQualityMinimum: 20,
  setTradeValueQualityMaximum: 21,
  setTradeValueQualityExponent: 22,
  setTradeValueTierQuality: 23,
} as const;

export const AetheriaRtsIpcChannels = {
  mapViewport: "aetheria-rts:map-viewport",
  objectsViewport: "aetheria-rts:objects-viewport",
  gravityViewport: "aetheria-rts:gravity-viewport",
  viewportFeed: "aetheria-rts:viewport-feed",
  viewportFeedStop: "aetheria-rts:viewport-feed-stop",
  viewportFeedUpdate: "aetheria-rts:viewport-feed-update",
  selectedObject: "aetheria-rts:selected-object",
  inventory: "aetheria-rts:inventory",
  daemonHealth: "aetheria-rts:daemon-health",
  authorityStatus: "aetheria-rts:authority-status",
  starbridgeSession: "aetheria-rts:starbridge-session",
  setMoveVector: "aetheria-rts:set-move-vector",
  setTarget: "aetheria-rts:set-target",
  surfaceCatalog: "aetheria-rts:surface-catalog",
  surfaceCatalogIndex: "aetheria-rts:surface-catalog-index",
  health: "aetheria-rts:health",
} as const;

export type AetheriaRuntimeDaemonCommandDocumentSlot =
  | "schema"
  | "commandId"
  | "clientId"
  | "issuedAtUtc"
  | "sessionId"
  | "observedFrameId"
  | "kind"
  | "actorEntityKey"
  | "targetEntityKey"
  | "targetZoneIndex"
  | "equipmentIndex"
  | "behaviorIndex"
  | "weaponGroup"
  | "positionX"
  | "positionY"
  | "positionZ"
  | "directionX"
  | "directionY"
  | "scalarValue"
  | "textValue"
  | "cargoTransfer"
  | "tradePurchase"
  | "lootPickup"
  | "loadoutRestore"
  | "equipmentTransfer"
  | "storeItem"
  | "authorRuntimeId"
  | "subjectKey"
  | "claimKind";

export const aetheriaRuntimeDaemonCommandDocumentSlots: Record<AetheriaRuntimeDaemonCommandDocumentSlot, number> = {
  schema: 0,
  commandId: 1,
  clientId: 2,
  issuedAtUtc: 3,
  sessionId: 4,
  observedFrameId: 5,
  kind: 6,
  actorEntityKey: 7,
  targetEntityKey: 8,
  targetZoneIndex: 9,
  equipmentIndex: 10,
  behaviorIndex: 11,
  weaponGroup: 12,
  positionX: 13,
  positionY: 14,
  positionZ: 15,
  directionX: 16,
  directionY: 17,
  scalarValue: 18,
  textValue: 19,
  cargoTransfer: 21,
  tradePurchase: 22,
  lootPickup: 23,
  loadoutRestore: 24,
  equipmentTransfer: 25,
  storeItem: 26,
  authorRuntimeId: 27,
  subjectKey: 28,
  claimKind: 29,
};

export type AetheriaRuntimeEveCommandDocumentSlot =
  | "schema"
  | "commandId"
  | "providerId"
  | "surfaceId"
  | "command"
  | "issuedAtUtc"
  | "clientId"
  | "playerSettings"
  | "loadoutTemplate"
  | "inputSettings"
  | "tradeValuePolicy"
  | "operationId"
  | "operationSchemaId"
  | "operationRouteKind"
  | "operationRouteDescription"
  | "operationIdempotencyKey"
  | "payload"
  | "operation";

export const aetheriaRuntimeEveCommandDocumentSlots: Record<AetheriaRuntimeEveCommandDocumentSlot, number> = {
  schema: 0,
  commandId: 1,
  providerId: 2,
  surfaceId: 3,
  command: 4,
  issuedAtUtc: 5,
  clientId: 6,
  playerSettings: 7,
  loadoutTemplate: 8,
  inputSettings: 9,
  tradeValuePolicy: 10,
  operationId: 11,
  operationSchemaId: 12,
  operationRouteKind: 13,
  operationRouteDescription: 14,
  operationIdempotencyKey: 15,
  payload: 16,
  operation: 17,
};

export type AetheriaRuntimeDaemonFrameDocumentSlot =
  | "schema"
  | "daemonId"
  | "sessionId"
  | "frameId"
  | "publishedAtUtc"
  | "simulationTimeSeconds"
  | "fixedDeltaSeconds"
  | "isAuthoritative"
  | "stateSource"
  | "run"
  | "capabilities"
  | "appliedCommandIds"
  | "rejectedCommandIds"
  | "accountedCommandIds"
  | "cumulativeAppliedCommandIds"
  | "cumulativeRejectedCommandIds"
  | "importedFactIds"
  | "rejectedImportedFactIds"
  | "duplicateImportedFactIds"
  | "cumulativeImportedFactIds"
  | "cumulativeRejectedImportedFactIds";

export const aetheriaRuntimeDaemonFrameDocumentSlots: Record<AetheriaRuntimeDaemonFrameDocumentSlot, number> = {
  schema: 0,
  daemonId: 1,
  sessionId: 2,
  frameId: 3,
  publishedAtUtc: 4,
  simulationTimeSeconds: 5,
  fixedDeltaSeconds: 6,
  isAuthoritative: 7,
  stateSource: 8,
  run: 9,
  capabilities: 10,
  appliedCommandIds: 11,
  rejectedCommandIds: 12,
  accountedCommandIds: 13,
  cumulativeAppliedCommandIds: 14,
  cumulativeRejectedCommandIds: 15,
  importedFactIds: 16,
  rejectedImportedFactIds: 17,
  duplicateImportedFactIds: 18,
  cumulativeImportedFactIds: 19,
  cumulativeRejectedImportedFactIds: 20,
};

export type AetheriaRuntimeDaemonHealthDocumentSlot =
  | "schema"
  | "daemonId"
  | "verseId"
  | "publishedAtUtc"
  | "statePath"
  | "frameId"
  | "observedCommandCount"
  | "appliedCommandCount"
  | "rejectedCommandCount"
  | "status"
  | "publicationSource"
  | "transport"
  | "commandBoundaryPath";

export const aetheriaRuntimeDaemonHealthDocumentSlots: Record<AetheriaRuntimeDaemonHealthDocumentSlot, number> = {
  schema: 0,
  daemonId: 1,
  verseId: 2,
  publishedAtUtc: 3,
  statePath: 4,
  frameId: 5,
  observedCommandCount: 6,
  appliedCommandCount: 7,
  rejectedCommandCount: 8,
  status: 9,
  publicationSource: 10,
  transport: 11,
  commandBoundaryPath: 12,
};

export type AetheriaRuntimeRtsViewportDocumentSlot =
  | "schema"
  | "frameId"
  | "publishedAtUtc"
  | "simulationTimeSeconds"
  | "runId"
  | "zoneIndex"
  | "zoneName"
  | "currentEntityKey"
  | "viewport"
  | "controlledEntityIndices"
  | "objects"
  | "gravityInfluences"
  | "bodies";

export const aetheriaRuntimeRtsViewportDocumentSlots: Record<AetheriaRuntimeRtsViewportDocumentSlot, number> = {
  schema: 0,
  frameId: 1,
  publishedAtUtc: 2,
  simulationTimeSeconds: 3,
  runId: 4,
  zoneIndex: 5,
  zoneName: 6,
  currentEntityKey: 7,
  viewport: 8,
  controlledEntityIndices: 9,
  objects: 10,
  gravityInfluences: 11,
  bodies: 12,
};

export type AetheriaRuntimeObjectsViewportDocumentSlot =
  | "schema"
  | "frameId"
  | "publishedAtUtc"
  | "simulationTimeSeconds"
  | "runId"
  | "zoneIndex"
  | "zoneName"
  | "currentEntityKey"
  | "viewport"
  | "controlledEntityIndices"
  | "objects";

export const aetheriaRuntimeObjectsViewportDocumentSlots: Record<AetheriaRuntimeObjectsViewportDocumentSlot, number> = {
  schema: 0,
  frameId: 1,
  publishedAtUtc: 2,
  simulationTimeSeconds: 3,
  runId: 4,
  zoneIndex: 5,
  zoneName: 6,
  currentEntityKey: 7,
  viewport: 8,
  controlledEntityIndices: 9,
  objects: 10,
};

export type AetheriaRuntimeGravityViewportDocumentSlot =
  | "schema"
  | "frameId"
  | "publishedAtUtc"
  | "simulationTimeSeconds"
  | "runId"
  | "zoneIndex"
  | "zoneName"
  | "viewport"
  | "gravityInfluences"
  | "bodies"
  | "terrainRadius"
  | "terrainDepth"
  | "terrainDepthExponent"
  | "terrainWaveFrequency";

export const aetheriaRuntimeGravityViewportDocumentSlots: Record<AetheriaRuntimeGravityViewportDocumentSlot, number> = {
  schema: 0,
  frameId: 1,
  publishedAtUtc: 2,
  simulationTimeSeconds: 3,
  runId: 4,
  zoneIndex: 5,
  zoneName: 6,
  viewport: 7,
  gravityInfluences: 8,
  bodies: 9,
  terrainRadius: 10,
  terrainDepth: 11,
  terrainDepthExponent: 12,
  terrainWaveFrequency: 13,
};

export type AetheriaRuntimeCurrentZoneDocumentSlot =
  | "schema"
  | "frameId"
  | "publishedAtUtc"
  | "simulationTimeSeconds"
  | "runId"
  | "zoneIndex"
  | "zoneName"
  | "positionX"
  | "positionY"
  | "currentEntityKey"
  | "adjacentZoneIndices";

export const aetheriaRuntimeCurrentZoneDocumentSlots: Record<AetheriaRuntimeCurrentZoneDocumentSlot, number> = {
  schema: 0,
  frameId: 1,
  publishedAtUtc: 2,
  simulationTimeSeconds: 3,
  runId: 4,
  zoneIndex: 5,
  zoneName: 6,
  positionX: 7,
  positionY: 8,
  currentEntityKey: 9,
  adjacentZoneIndices: 10,
};

export type AetheriaRuntimeCurrentEntityDocumentSlot =
  | "schema"
  | "frameId"
  | "publishedAtUtc"
  | "simulationTimeSeconds"
  | "runId"
  | "zoneIndex"
  | "entityKey"
  | "entityIndex"
  | "entity"
  | "status"
  | "inventory"
  | "equipment"
  | "cargo"
  | "shutdownPerformance"
  | "hud";

export const aetheriaRuntimeCurrentEntityDocumentSlots: Record<AetheriaRuntimeCurrentEntityDocumentSlot, number> = {
  schema: 0,
  frameId: 1,
  publishedAtUtc: 2,
  simulationTimeSeconds: 3,
  runId: 4,
  zoneIndex: 5,
  entityKey: 6,
  entityIndex: 7,
  entity: 8,
  status: 9,
  inventory: 10,
  equipment: 11,
  cargo: 12,
  shutdownPerformance: 13,
  hud: 14,
};

export type AetheriaRuntimeCurrentDockingDocumentSlot =
  | "schema"
  | "frameId"
  | "publishedAtUtc"
  | "simulationTimeSeconds"
  | "runId"
  | "zoneIndex"
  | "currentEntityKey"
  | "currentEntityIndex"
  | "isDocked"
  | "dockParentEntityKey"
  | "dockParentEntityIndex"
  | "dockingBayIndex"
  | "dockParent"
  | "dockParentOrbitKey"
  | "dockParentParentOrbitKey"
  | "dockParentParentBodyKey";

export const aetheriaRuntimeCurrentDockingDocumentSlots: Record<AetheriaRuntimeCurrentDockingDocumentSlot, number> = {
  schema: 0,
  frameId: 1,
  publishedAtUtc: 2,
  simulationTimeSeconds: 3,
  runId: 4,
  zoneIndex: 5,
  currentEntityKey: 6,
  currentEntityIndex: 7,
  isDocked: 8,
  dockParentEntityKey: 9,
  dockParentEntityIndex: 10,
  dockingBayIndex: 11,
  dockParent: 12,
  dockParentOrbitKey: 13,
  dockParentParentOrbitKey: 14,
  dockParentParentBodyKey: 15,
};

export type AetheriaRuntimeStationRefitDocumentSlot =
  | "schema"
  | "frameId"
  | "publishedAtUtc"
  | "simulationTimeSeconds"
  | "runId"
  | "zoneIndex"
  | "currentEntityKey"
  | "currentEntityIndex"
  | "isDocked"
  | "dockParentEntityKey"
  | "dockParentEntityIndex"
  | "dockingBayIndex"
  | "dockParent"
  | "availableEntities"
  | "credits"
  | "stationStock"
  | "dockingBays"
  | "loadoutRestoreOptions"
  | "cargoTargets";

export const aetheriaRuntimeStationRefitDocumentSlots: Record<AetheriaRuntimeStationRefitDocumentSlot, number> = {
  schema: 0,
  frameId: 1,
  publishedAtUtc: 2,
  simulationTimeSeconds: 3,
  runId: 4,
  zoneIndex: 5,
  currentEntityKey: 6,
  currentEntityIndex: 7,
  isDocked: 8,
  dockParentEntityKey: 9,
  dockParentEntityIndex: 10,
  dockingBayIndex: 11,
  dockParent: 12,
  availableEntities: 13,
  credits: 14,
  stationStock: 15,
  dockingBays: 16,
  loadoutRestoreOptions: 17,
  cargoTargets: 18,
};

export type AetheriaRuntimeStationRefitEntityOptionSlot =
  | "entityKey"
  | "entityIndex"
  | "displayName"
  | "kind"
  | "isCurrentEntity"
  | "isPlayerShip"
  | "cargoBayCount"
  | "dockingBayIndex"
  | "hullItemKey"
  | "cargoItems";

export const aetheriaRuntimeStationRefitEntityOptionSlots: Record<AetheriaRuntimeStationRefitEntityOptionSlot, number> = {
  entityKey: 0,
  entityIndex: 1,
  displayName: 2,
  kind: 3,
  isCurrentEntity: 4,
  isPlayerShip: 5,
  cargoBayCount: 6,
  dockingBayIndex: 7,
  hullItemKey: 8,
  cargoItems: 9,
};

export type AetheriaRuntimeStationStockItemSlot =
  | "itemKey"
  | "quantity"
  | "quality"
  | "durability"
  | "cargoBayIndex"
  | "x"
  | "y"
  | "price"
  | "canAfford"
  | "ownedQuantity";

export const aetheriaRuntimeStationStockItemSlots: Record<AetheriaRuntimeStationStockItemSlot, number> = {
  itemKey: 0,
  quantity: 1,
  quality: 2,
  durability: 3,
  cargoBayIndex: 4,
  x: 5,
  y: 6,
  price: 7,
  canAfford: 8,
  ownedQuantity: 9,
};

export type AetheriaRuntimeSectorMapDocumentSlot =
  | "schema"
  | "frameId"
  | "publishedAtUtc"
  | "simulationTimeSeconds"
  | "runId"
  | "currentZoneIndex"
  | "entranceZoneIndex"
  | "exitZoneIndex"
  | "discoveredZoneIndices"
  | "zones"
  | "links"
  | "isTutorial"
  | "generationSeed"
  | "factionRelationships";

export const aetheriaRuntimeSectorMapDocumentSlots: Record<AetheriaRuntimeSectorMapDocumentSlot, number> = {
  schema: 0,
  frameId: 1,
  publishedAtUtc: 2,
  simulationTimeSeconds: 3,
  runId: 4,
  currentZoneIndex: 5,
  entranceZoneIndex: 6,
  exitZoneIndex: 7,
  discoveredZoneIndices: 8,
  zones: 9,
  links: 10,
  isTutorial: 11,
  generationSeed: 12,
  factionRelationships: 13,
};

export type AetheriaRuntimeSectorMapZoneSlot =
  | "zoneIndex"
  | "name"
  | "x"
  | "y"
  | "ownerFactionIndex"
  | "factionIndices"
  | "adjacentZoneIndices"
  | "discovered"
  | "current"
  | "entrance"
  | "exit";

export const aetheriaRuntimeSectorMapZoneSlots: Record<AetheriaRuntimeSectorMapZoneSlot, number> = {
  zoneIndex: 0,
  name: 1,
  x: 2,
  y: 3,
  ownerFactionIndex: 4,
  factionIndices: 5,
  adjacentZoneIndices: 6,
  discovered: 7,
  current: 8,
  entrance: 9,
  exit: 10,
};

export type AetheriaRuntimeSectorMapLinkSlot =
  | "fromZoneIndex"
  | "toZoneIndex"
  | "discovered";

export const aetheriaRuntimeSectorMapLinkSlots: Record<AetheriaRuntimeSectorMapLinkSlot, number> = {
  fromZoneIndex: 0,
  toZoneIndex: 1,
  discovered: 2,
};

export type AetheriaRuntimeZoneRenderDocumentSlot =
  | "schema"
  | "frameId"
  | "publishedAtUtc"
  | "simulationTimeSeconds"
  | "runId"
  | "zoneIndex"
  | "zoneName"
  | "currentEntityKey"
  | "zoneRenderRadius"
  | "credits"
  | "adjacentZones"
  | "bodyPoses"
  | "asteroidBeltPoses"
  | "wormholeExits"
  | "droppedPickups"
  | "entityFacades"
  | "orbits"
  | "bodies";

export const aetheriaRuntimeZoneRenderDocumentSlots: Record<AetheriaRuntimeZoneRenderDocumentSlot, number> = {
  schema: 0,
  frameId: 1,
  publishedAtUtc: 2,
  simulationTimeSeconds: 3,
  runId: 4,
  zoneIndex: 5,
  zoneName: 6,
  currentEntityKey: 7,
  zoneRenderRadius: 8,
  credits: 9,
  adjacentZones: 12,
  bodyPoses: 13,
  asteroidBeltPoses: 14,
  wormholeExits: 15,
  droppedPickups: 16,
  entityFacades: 17,
  orbits: 18,
  bodies: 19,
};

export type AetheriaRuntimeZoneRenderBodyPoseSlot =
  | "bodyKey"
  | "orbitKey"
  | "parentOrbitKey"
  | "kind"
  | "centerX"
  | "centerZ"
  | "parentCenterX"
  | "parentCenterZ"
  | "gravityWaveSpeed";

export const aetheriaRuntimeZoneRenderBodyPoseSlots: Record<AetheriaRuntimeZoneRenderBodyPoseSlot, number> = {
  bodyKey: 0,
  orbitKey: 1,
  parentOrbitKey: 2,
  kind: 3,
  centerX: 4,
  centerZ: 5,
  parentCenterX: 6,
  parentCenterZ: 7,
  gravityWaveSpeed: 8,
};

export type AetheriaRuntimeZoneRenderAsteroidBeltPoseSlot =
  | "bodyKey"
  | "orbitKey"
  | "centerX"
  | "centerZ"
  | "radius"
  | "asteroidCount"
  | "instancePoses";

export const aetheriaRuntimeZoneRenderAsteroidBeltPoseSlots: Record<AetheriaRuntimeZoneRenderAsteroidBeltPoseSlot, number> = {
  bodyKey: 0,
  orbitKey: 1,
  centerX: 2,
  centerZ: 3,
  radius: 4,
  asteroidCount: 5,
  instancePoses: 6,
};

export type AetheriaRuntimeSelectedObjectDocumentSlot =
  | "schema"
  | "frameId"
  | "runId"
  | "zoneIndex"
  | "entityIndex"
  | "selected";

export const aetheriaRuntimeSelectedObjectDocumentSlots: Record<AetheriaRuntimeSelectedObjectDocumentSlot, number> = {
  schema: 0,
  frameId: 1,
  runId: 2,
  zoneIndex: 3,
  entityIndex: 4,
  selected: 5,
};

export type AetheriaRuntimeInventoryDocumentSlot =
  | "schema"
  | "frameId"
  | "runId"
  | "zoneIndex"
  | "entityIndex"
  | "entityKey"
  | "items"
  | "equipment"
  | "cargo";

export const aetheriaRuntimeInventoryDocumentSlots: Record<AetheriaRuntimeInventoryDocumentSlot, number> = {
  schema: 0,
  frameId: 1,
  runId: 2,
  zoneIndex: 3,
  entityIndex: 4,
  entityKey: 5,
  items: 6,
  equipment: 7,
  cargo: 8,
};

export type AetheriaRuntimeRunCheckpointCommitSlot =
  | "runId"
  | "isTutorial"
  | "entranceZoneIndex"
  | "exitZoneIndex"
  | "currentZoneIndex"
  | "discoveredZoneIndices"
  | "zones"
  | "factionRelationships"
  | "generationSeed"
  | "currentEntityKey"
  | "credits";

export const aetheriaRuntimeRunCheckpointCommitSlots: Record<AetheriaRuntimeRunCheckpointCommitSlot, number> = {
  runId: 0,
  isTutorial: 1,
  entranceZoneIndex: 2,
  exitZoneIndex: 3,
  currentZoneIndex: 4,
  discoveredZoneIndices: 5,
  zones: 6,
  factionRelationships: 8,
  generationSeed: 9,
  currentEntityKey: 10,
  credits: 11,
};

export type AetheriaRuntimeZoneSnapshotCommitSlot =
  | "zoneIndex"
  | "name"
  | "positionX"
  | "positionY"
  | "adjacentZoneIndices"
  | "factionIndices"
  | "ownerFactionIndex"
  | "entities"
  | "orbits"
  | "bodies"
  | "droppedPickups"
  | "gravityTerrainRadius"
  | "gravityTerrainDepth"
  | "gravityTerrainDepthExponent"
  | "gravityTerrainBoundaryFog"
  | "gravityTerrainWaveFrequency"
  | "simulationTimeSeconds";

export const aetheriaRuntimeZoneSnapshotCommitSlots: Record<AetheriaRuntimeZoneSnapshotCommitSlot, number> = {
  zoneIndex: 0,
  name: 1,
  positionX: 2,
  positionY: 3,
  adjacentZoneIndices: 4,
  factionIndices: 5,
  ownerFactionIndex: 6,
  entities: 7,
  orbits: 8,
  bodies: 9,
  droppedPickups: 10,
  gravityTerrainRadius: 11,
  gravityTerrainDepth: 12,
  gravityTerrainDepthExponent: 13,
  gravityTerrainBoundaryFog: 14,
  gravityTerrainWaveFrequency: 15,
  simulationTimeSeconds: 16,
};

export type AetheriaRuntimeEntitySnapshotCommitSlot =
  | "entityIndex"
  | "name"
  | "kind"
  | "positionX"
  | "positionY"
  | "positionZ"
  | "directionX"
  | "directionY"
  | "equipment"
  | "cargoBays"
  | "dockingBays"
  | "childEntityIndices"
  | "weaponGroups"
  | "statGrids"
  | "velocityX"
  | "velocityY"
  | "targetEntityIndex"
  | "isActive"
  | "heatsinksEnabled"
  | "overrideShutdown"
  | "tractorPower"
  | "heatstroke"
  | "hypothermia"
  | "activeConsumables"
  | "behaviorProgress"
  | "weaponStates"
  | "behaviorStates"
  | "cargoContents"
  | "dockingBayContents"
  | "dockingBayAssignments"
  | "visibility"
  | "visibilitySourceCount"
  | "contacts"
  | "hullItemKey"
  | "factionKey"
  | "shutdownPerformance";

export const aetheriaRuntimeEntitySnapshotCommitSlots: Record<AetheriaRuntimeEntitySnapshotCommitSlot, number> = {
  entityIndex: 0,
  name: 1,
  kind: 2,
  positionX: 3,
  positionY: 4,
  positionZ: 5,
  directionX: 6,
  directionY: 7,
  equipment: 10,
  cargoBays: 11,
  dockingBays: 12,
  childEntityIndices: 13,
  weaponGroups: 14,
  statGrids: 15,
  velocityX: 16,
  velocityY: 17,
  targetEntityIndex: 18,
  isActive: 19,
  heatsinksEnabled: 20,
  overrideShutdown: 21,
  tractorPower: 22,
  heatstroke: 23,
  hypothermia: 24,
  activeConsumables: 25,
  behaviorProgress: 26,
  weaponStates: 27,
  behaviorStates: 28,
  cargoContents: 29,
  dockingBayContents: 30,
  dockingBayAssignments: 31,
  visibility: 32,
  visibilitySourceCount: 33,
  contacts: 34,
  hullItemKey: 35,
  factionKey: 36,
  shutdownPerformance: 37,
};

export type AetheriaRuntimeBodySnapshotCommitSlot =
  | "kind"
  | "name"
  | "mass"
  | "resources"
  | "bodyRadiusMultiplier"
  | "gravityRadiusMultiplier"
  | "gravityDepthMultiplier"
  | "gravityDepthExponent"
  | "asteroids"
  | "gasGiantVisual"
  | "sunVisual"
  | "bodyKey"
  | "orbitKey"
  | "gravityInfluenceCenterX"
  | "gravityInfluenceCenterZ"
  | "gravityInfluenceRadius"
  | "gravityWellDepth"
  | "gravityWaveRadius"
  | "gravityWaveDepth"
  | "gravityWaveSpeed";

export const aetheriaRuntimeBodySnapshotCommitSlots: Record<AetheriaRuntimeBodySnapshotCommitSlot, number> = {
  kind: 1,
  name: 2,
  mass: 4,
  resources: 5,
  bodyRadiusMultiplier: 6,
  gravityRadiusMultiplier: 7,
  gravityDepthMultiplier: 8,
  gravityDepthExponent: 9,
  asteroids: 10,
  gasGiantVisual: 11,
  sunVisual: 12,
  bodyKey: 13,
  orbitKey: 14,
  gravityInfluenceCenterX: 15,
  gravityInfluenceCenterZ: 16,
  gravityInfluenceRadius: 17,
  gravityWellDepth: 18,
  gravityWaveRadius: 19,
  gravityWaveDepth: 20,
  gravityWaveSpeed: 21,
};

export type AetheriaRuntimeEntityStatGridCommitSlot =
  | "name"
  | "width"
  | "height"
  | "values";

export const aetheriaRuntimeEntityStatGridCommitSlots: Record<AetheriaRuntimeEntityStatGridCommitSlot, number> = {
  name: 0,
  width: 1,
  height: 2,
  values: 3,
};

export type AetheriaRuntimeCargoBayLoadoutCommitSlot =
  | "items";

export const aetheriaRuntimeCargoBayLoadoutCommitSlots: Record<AetheriaRuntimeCargoBayLoadoutCommitSlot, number> = {
  items: 0,
};

export type AetheriaRuntimeLoadoutItemSlotCommitSlot =
  | "x"
  | "y"
  | "item";

export const aetheriaRuntimeLoadoutItemSlotCommitSlots: Record<AetheriaRuntimeLoadoutItemSlotCommitSlot, number> = {
  x: 0,
  y: 1,
  item: 2,
};

export type AetheriaRuntimeLoadoutItemCommitSlot =
  | "quality"
  | "durability"
  | "quantity"
  | "enabled"
  | "itemKey"
  | "overrideShutdown"
  | "temperature";

export const aetheriaRuntimeLoadoutItemCommitSlots: Record<AetheriaRuntimeLoadoutItemCommitSlot, number> = {
  quality: 1,
  durability: 2,
  quantity: 3,
  enabled: 4,
  itemKey: 5,
  overrideShutdown: 6,
  temperature: 7,
};

export type AetheriaRuntimeRtsViewportBoundsSlot =
  | "minX"
  | "minY"
  | "maxX"
  | "maxY";

export const aetheriaRuntimeRtsViewportBoundsSlots: Record<AetheriaRuntimeRtsViewportBoundsSlot, number> = {
  minX: 0,
  minY: 1,
  maxX: 2,
  maxY: 3,
};

export type AetheriaRuntimeRtsViewportObjectSlot =
  | "entityIndex"
  | "entityKey"
  | "displayName"
  | "kind"
  | "factionKey"
  | "x"
  | "y"
  | "z"
  | "directionX"
  | "directionY"
  | "velocityX"
  | "velocityY"
  | "controlled"
  | "targetEntityIndex"
  | "isActive"
  | "visibility"
  | "status"
  | "inventory";

export const aetheriaRuntimeRtsViewportObjectSlots: Record<AetheriaRuntimeRtsViewportObjectSlot, number> = {
  entityIndex: 0,
  entityKey: 1,
  displayName: 2,
  kind: 3,
  factionKey: 4,
  x: 5,
  y: 6,
  z: 7,
  directionX: 8,
  directionY: 9,
  velocityX: 10,
  velocityY: 11,
  controlled: 12,
  targetEntityIndex: 13,
  isActive: 14,
  visibility: 15,
  status: 16,
  inventory: 17,
};

export type AetheriaRuntimeRtsEntityStatusSlot =
  | "hull"
  | "shield"
  | "heat";

export const aetheriaRuntimeRtsEntityStatusSlots: Record<AetheriaRuntimeRtsEntityStatusSlot, number> = {
  hull: 0,
  shield: 1,
  heat: 2,
};

export type AetheriaRuntimeRtsInventoryItemSlot =
  | "source"
  | "itemKey"
  | "quantity"
  | "quality"
  | "durability"
  | "enabled"
  | "sourceIndex"
  | "x"
  | "y";

export const aetheriaRuntimeRtsInventoryItemSlots: Record<AetheriaRuntimeRtsInventoryItemSlot, number> = {
  source: 0,
  itemKey: 1,
  quantity: 2,
  quality: 3,
  durability: 4,
  enabled: 5,
  sourceIndex: 6,
  x: 7,
  y: 8,
};

export type AetheriaRuntimeRtsGravityInfluenceSlot =
  | "bodyKey"
  | "orbitKey"
  | "kind"
  | "x"
  | "y"
  | "radius"
  | "gravityDepth"
  | "gravityDepthExponent"
  | "waveRadius"
  | "waveDepth"
  | "waveSpeed";

export const aetheriaRuntimeRtsGravityInfluenceSlots: Record<AetheriaRuntimeRtsGravityInfluenceSlot, number> = {
  bodyKey: 0,
  orbitKey: 1,
  kind: 2,
  x: 3,
  y: 4,
  radius: 5,
  gravityDepth: 6,
  gravityDepthExponent: 7,
  waveRadius: 8,
  waveDepth: 9,
  waveSpeed: 10,
};

export type AetheriaRuntimeRtsBodyViewSlot =
  | "bodyKey"
  | "orbitKey"
  | "name"
  | "kind"
  | "x"
  | "y"
  | "radius"
  | "isAsteroidBelt"
  | "body";

export const aetheriaRuntimeRtsBodyViewSlots: Record<AetheriaRuntimeRtsBodyViewSlot, number> = {
  bodyKey: 0,
  orbitKey: 1,
  name: 2,
  kind: 3,
  x: 4,
  y: 5,
  radius: 6,
  isAsteroidBelt: 7,
  body: 8,
};

export type AetheriaRuntimeStarbridgeScenarioDocumentSlot =
  | "schema"
  | "scenarioId"
  | "displayName"
  | "startingBaseKey"
  | "stationStock"
  | "availableShipKeys"
  | "waves"
  | "attackerMixKeys"
  | "recoveredTechnologyPoolKeys"
  | "runtimeRoles";

export const aetheriaRuntimeStarbridgeScenarioDocumentSlots: Record<AetheriaRuntimeStarbridgeScenarioDocumentSlot, number> = {
  schema: 0,
  scenarioId: 1,
  displayName: 2,
  startingBaseKey: 3,
  stationStock: 4,
  availableShipKeys: 5,
  waves: 6,
  attackerMixKeys: 7,
  recoveredTechnologyPoolKeys: 8,
  runtimeRoles: 9,
};

export type AetheriaRuntimeStarbridgeSessionDocumentSlot =
  | "schema"
  | "sessionId"
  | "scenarioId"
  | "runId"
  | "baseEntityKey"
  | "stationEntityKey"
  | "phase"
  | "currentWaveIndex"
  | "runtimeRoles";

export const aetheriaRuntimeStarbridgeSessionDocumentSlots: Record<AetheriaRuntimeStarbridgeSessionDocumentSlot, number> = {
  schema: 0,
  sessionId: 1,
  scenarioId: 2,
  runId: 3,
  baseEntityKey: 4,
  stationEntityKey: 5,
  phase: 6,
  currentWaveIndex: 7,
  runtimeRoles: 8,
};

export type AetheriaRuntimeStarbridgeSessionSummaryDocumentSlot =
  | "schema"
  | "frameId"
  | "publishedAtUtc"
  | "sessionId"
  | "scenarioId"
  | "scenarioName"
  | "runId"
  | "zoneIndex"
  | "zoneName"
  | "phase"
  | "currentWaveIndex"
  | "baseStatus"
  | "stationStock"
  | "waveForecast"
  | "runtimeRoles";

export const aetheriaRuntimeStarbridgeSessionSummaryDocumentSlots: Record<AetheriaRuntimeStarbridgeSessionSummaryDocumentSlot, number> = {
  schema: 0,
  frameId: 1,
  publishedAtUtc: 2,
  sessionId: 3,
  scenarioId: 4,
  scenarioName: 5,
  runId: 6,
  zoneIndex: 7,
  zoneName: 8,
  phase: 9,
  currentWaveIndex: 10,
  baseStatus: 11,
  stationStock: 12,
  waveForecast: 13,
  runtimeRoles: 14,
};

export type AetheriaRuntimeStarbridgeStationStockItemSlot =
  | "itemKey"
  | "quantity"
  | "quality"
  | "durability"
  | "source";

export const aetheriaRuntimeStarbridgeStationStockItemSlots: Record<AetheriaRuntimeStarbridgeStationStockItemSlot, number> = {
  itemKey: 0,
  quantity: 1,
  quality: 2,
  durability: 3,
  source: 4,
};

export type AetheriaRuntimeStarbridgeWaveDefinitionSlot =
  | "waveIndex"
  | "displayName"
  | "attackerKeys"
  | "startsAfterSeconds"
  | "bossKey"
  | "recoveredTechnologyKeys";

export const aetheriaRuntimeStarbridgeWaveDefinitionSlots: Record<AetheriaRuntimeStarbridgeWaveDefinitionSlot, number> = {
  waveIndex: 0,
  displayName: 1,
  attackerKeys: 2,
  startsAfterSeconds: 3,
  bossKey: 4,
  recoveredTechnologyKeys: 5,
};

export type AetheriaRuntimeStarbridgeWaveForecastSlot =
  | "waveIndex"
  | "displayName"
  | "attackerKeys"
  | "bossKey"
  | "recoveredTechnologyKeys";

export const aetheriaRuntimeStarbridgeWaveForecastSlots: Record<AetheriaRuntimeStarbridgeWaveForecastSlot, number> = {
  waveIndex: 0,
  displayName: 1,
  attackerKeys: 2,
  bossKey: 3,
  recoveredTechnologyKeys: 4,
};

export type AetheriaRuntimeStarbridgeRuntimeRoleSlot =
  | "runtimeId"
  | "role"
  | "entityKey";

export const aetheriaRuntimeStarbridgeRuntimeRoleSlots: Record<AetheriaRuntimeStarbridgeRuntimeRoleSlot, number> = {
  runtimeId: 0,
  role: 1,
  entityKey: 2,
};

export type AetheriaRuntimeStarbridgeBaseStatusSlot =
  | "entityKey"
  | "displayName"
  | "hull"
  | "shield"
  | "heat"
  | "isActive";

export const aetheriaRuntimeStarbridgeBaseStatusSlots: Record<AetheriaRuntimeStarbridgeBaseStatusSlot, number> = {
  entityKey: 0,
  displayName: 1,
  hull: 2,
  shield: 3,
  heat: 4,
  isActive: 5,
};

export type AetheriaRuntimeVerseAuthorityPolicyDocumentSlot =
  | "schema"
  | "verseId"
  | "policyId"
  | "ruleVersion"
  | "hostRuntimeId"
  | "defaultMode"
  | "rules"
  | "updatedAtUtc"
  | "deploymentMode"
  | "runtimeRoles";

export const aetheriaRuntimeVerseAuthorityPolicyDocumentSlots: Record<AetheriaRuntimeVerseAuthorityPolicyDocumentSlot, number> = {
  schema: 0,
  verseId: 1,
  policyId: 2,
  ruleVersion: 3,
  hostRuntimeId: 4,
  defaultMode: 5,
  rules: 6,
  updatedAtUtc: 7,
  deploymentMode: 8,
  runtimeRoles: 9,
};

export type AetheriaRuntimeAuthorityRuleSlot =
  | "ruleId"
  | "subjectPrefix"
  | "claimKinds"
  | "mode"
  | "runtimeIds"
  | "leaseScope"
  | "priority";

export const aetheriaRuntimeAuthorityRuleSlots: Record<AetheriaRuntimeAuthorityRuleSlot, number> = {
  ruleId: 0,
  subjectPrefix: 1,
  claimKinds: 2,
  mode: 3,
  runtimeIds: 4,
  leaseScope: 5,
  priority: 6,
};

export type AetheriaRuntimeAuthorityRuntimeRoleSlot =
  | "runtimeId"
  | "roles";

export const aetheriaRuntimeAuthorityRuntimeRoleSlots: Record<AetheriaRuntimeAuthorityRuntimeRoleSlot, number> = {
  runtimeId: 0,
  roles: 1,
};

export type AetheriaRuntimeAuthorityLeaseDocumentSlot =
  | "schema"
  | "leaseId"
  | "verseId"
  | "runtimeId"
  | "subjectPrefix"
  | "claimKinds"
  | "validFromUtc"
  | "expiresAtUtc"
  | "scope";

export const aetheriaRuntimeAuthorityLeaseDocumentSlots: Record<AetheriaRuntimeAuthorityLeaseDocumentSlot, number> = {
  schema: 0,
  leaseId: 1,
  verseId: 2,
  runtimeId: 3,
  subjectPrefix: 4,
  claimKinds: 5,
  validFromUtc: 6,
  expiresAtUtc: 7,
  scope: 8,
};

export type ViewportResponse = {
  schema: string;
  frameId: number;
  publishedAtUtc: string;
  simulationTimeSeconds: number;
  runId: string;
  zoneIndex: number;
  zoneName: string;
  currentEntityKey: string;
  viewport: CultMeshViewportRequest;
  controlledEntityIndices: number[];
  objects: ViewObject[];
  gravityInfluences: GravityInfluence[];
  bodies: BodyView[];
};

export type ObjectsViewportResponse = {
  schema: string;
  frameId: number;
  publishedAtUtc: string;
  simulationTimeSeconds: number;
  runId: string;
  zoneIndex: number;
  zoneName: string;
  currentEntityKey: string;
  viewport: CultMeshViewportRequest;
  controlledEntityIndices: number[];
  objects: ViewObject[];
};

export type GravityViewportResponse = {
  schema: string;
  frameId: number;
  publishedAtUtc: string;
  simulationTimeSeconds: number;
  runId: string;
  zoneIndex: number;
  zoneName: string;
  viewport: CultMeshViewportRequest;
  gravityInfluences: GravityInfluence[];
  bodies: BodyView[];
};

export type ViewObject = {
  entityIndex: number;
  entityKey: string;
  displayName: string;
  kind: string;
  factionKey: string;
  x: number;
  y: number;
  z: number;
  directionX: number;
  directionY: number;
  velocityX: number;
  velocityY: number;
  controlled: boolean;
  targetEntityIndex: number;
  isActive: boolean;
  visibility: number;
  status: EntityStatus;
  inventory: InventoryItem[];
};

export type EntityStatus = {
  hull: number;
  shield: number;
  heat: number;
};

export type InventoryItem = {
  source: string;
  itemKey: string;
  quantity: number;
  quality: number;
  durability: number;
  enabled: boolean;
};

export type SelectedObjectProjection = {
  schema: string;
  frameId: number;
  runId: string;
  zoneIndex: number;
  entityIndex: number;
  selected: ViewObject | null;
};

export type InventoryProjection = {
  schema: string;
  frameId: number;
  runId: string;
  zoneIndex: number;
  entityIndex: number;
  entityKey: string;
  items: InventoryItem[];
  equipment: InventoryItem[];
  cargo: InventoryItem[];
};

export type DaemonHealthProjection = {
  schema: string;
  daemonId: string;
  verseId: string;
  publishedAtUtc: string;
  statePath: string;
  frameId: number;
  observedCommandCount: number;
  appliedCommandCount: number;
  rejectedCommandCount: number;
  status: string;
  publicationSource: string;
  transport: string;
  commandBoundaryPath: string;
};

export type AuthorityStatusProjection = {
  schema: string;
  verseId: string;
  policyId: string;
  ruleVersion: string;
  hostRuntimeId: string;
  defaultMode: string;
  updatedAtUtc: string;
  rules: AuthorityRuleProjection[];
};

export type AuthorityRuleProjection = {
  ruleId: string;
  subjectPrefix: string;
  claimKinds: string[];
  mode: string;
  runtimeIds: string[];
  leaseScope: string;
  priority: number;
};

export type StarbridgeSessionProjection = {
  schema: string;
  frameId: number;
  publishedAtUtc: string;
  sessionId: string;
  scenarioId: string;
  scenarioName: string;
  runId: string;
  zoneIndex: number;
  zoneName: string;
  phase: string;
  currentWaveIndex: number;
  baseStatus: StarbridgeBaseStatusProjection;
  stationStock: StarbridgeStationStockItemProjection[];
  waveForecast: StarbridgeWaveForecastProjection[];
  runtimeRoles: StarbridgeRuntimeRoleProjection[];
};

export type StarbridgeBaseStatusProjection = {
  entityKey: string;
  displayName: string;
  hull: number;
  shield: number;
  heat: number;
  isActive: boolean;
};

export type StarbridgeStationStockItemProjection = {
  itemKey: string;
  quantity: number;
  quality: number;
  durability: number;
  source: string;
};

export type StarbridgeWaveForecastProjection = {
  waveIndex: number;
  displayName: string;
  attackerKeys: string[];
  bossKey: string;
  recoveredTechnologyKeys: string[];
};

export type StarbridgeRuntimeRoleProjection = {
  runtimeId: string;
  role: string;
  entityKey: string;
};

export type GravityInfluence = {
  bodyKey: string;
  orbitKey: string;
  kind: string;
  x: number;
  y: number;
  radius: number;
  gravityDepth: number;
  gravityDepthExponent: number;
  waveRadius: number;
  waveDepth: number;
  waveSpeed: number;
};

export type BodyView = {
  bodyKey: string;
  orbitKey: string;
  name: string;
  kind: string;
  x: number;
  y: number;
  radius: number;
  isAsteroidBelt: boolean;
};


export type AetheriaRuntimeSetMoveVectorRequest = {
  actorEntityKey: string;
  directionX: number;
  directionY: number;
  scalar: number;
  observedFrameId?: number;
};

export type AetheriaRuntimeSetTargetRequest = {
  actorEntityKey: string;
  targetEntityKey: string;
  observedFrameId?: number;
};

export type AetheriaRuntimeDaemonCommandReceipt = CultMeshOperationReceipt & {
  commandId: string;
};

export type AetheriaRuntimeSelectedObjectRequest = {
  entityIndex: number;
};

export type AetheriaRuntimeViewportFeedRequest = {
  viewport: CultMeshViewportRequest;
  selectedEntityIndex?: number;
};

export type AetheriaRuntimeViewportFeedSnapshot = {
  viewport: ViewportResponse;
  selectedObject: SelectedObjectProjection | null;
  inventory: InventoryProjection | null;
  daemonHealth: DaemonHealthProjection;
  authorityStatus: AuthorityStatusProjection;
  starbridgeSession: StarbridgeSessionProjection;
  receivedAtUtc: string;
  sampleMs: number;
};

export type AetheriaRtsMainClient = {
  mapViewport(request: CultMeshViewportRequest): Promise<ViewportResponse>;
  objectsViewport(request: CultMeshViewportRequest): Promise<ObjectsViewportResponse>;
  gravityViewport(request: CultMeshViewportRequest): Promise<GravityViewportResponse>;
  selectedObject(request: AetheriaRuntimeSelectedObjectRequest): Promise<SelectedObjectProjection>;
  inventory(request: AetheriaRuntimeSelectedObjectRequest): Promise<InventoryProjection>;
  daemonHealth(): Promise<DaemonHealthProjection>;
  authorityStatus(): Promise<AuthorityStatusProjection>;
  starbridgeSession(): Promise<StarbridgeSessionProjection>;
  watchViewportFeed(request: AetheriaRuntimeViewportFeedRequest, callback: (snapshot: AetheriaRuntimeViewportFeedSnapshot) => void): CultMeshUnsubscribe;
  setMoveVector(request: AetheriaRuntimeSetMoveVectorRequest): Promise<AetheriaRuntimeDaemonCommandReceipt>;
  setTarget(request: AetheriaRuntimeSetTargetRequest): Promise<AetheriaRuntimeDaemonCommandReceipt>;
  surfaceCatalogDiagnostics(): CultMeshSurfaceCatalogDiagnostic;
  surfaceCatalogIndexDiagnostics(): CultMeshSurfaceCatalogIndexDiagnostic;
};

export type AetheriaRtsHealthProvider = () => unknown;

export function registerAetheriaRtsIpcHandlers(
  ipcMain: IpcMain,
  getClient: () => AetheriaRtsMainClient,
  getHealth: AetheriaRtsHealthProvider,
): void {
  const viewportFeedSubscriptions = new Map<string, CultMeshUnsubscribe>();
  ipcMain.handle(AetheriaRtsIpcChannels.mapViewport, async (_event, request: CultMeshViewportRequest) =>
    getClient().mapViewport(request));
  ipcMain.handle(AetheriaRtsIpcChannels.objectsViewport, async (_event, request: CultMeshViewportRequest) =>
    getClient().objectsViewport(request));
  ipcMain.handle(AetheriaRtsIpcChannels.gravityViewport, async (_event, request: CultMeshViewportRequest) =>
    getClient().gravityViewport(request));
  ipcMain.handle(AetheriaRtsIpcChannels.selectedObject, async (_event, request: AetheriaRuntimeSelectedObjectRequest) =>
    getClient().selectedObject(request));
  ipcMain.handle(AetheriaRtsIpcChannels.inventory, async (_event, request: AetheriaRuntimeSelectedObjectRequest) =>
    getClient().inventory(request));
  ipcMain.handle(AetheriaRtsIpcChannels.daemonHealth, async () => getClient().daemonHealth());
  ipcMain.handle(AetheriaRtsIpcChannels.authorityStatus, async () => getClient().authorityStatus());
  ipcMain.handle(AetheriaRtsIpcChannels.starbridgeSession, async () => getClient().starbridgeSession());
  ipcMain.handle(AetheriaRtsIpcChannels.viewportFeed, async (event, request: { subscriptionId: string; feed: AetheriaRuntimeViewportFeedRequest }) => {
    viewportFeedSubscriptions.get(request.subscriptionId)?.();
    const unsubscribe = getClient().watchViewportFeed(request.feed, snapshot => {
      event.sender.send(AetheriaRtsIpcChannels.viewportFeedUpdate, {
        subscriptionId: request.subscriptionId,
        snapshot,
      });
    });
    viewportFeedSubscriptions.set(request.subscriptionId, unsubscribe);
  });
  ipcMain.handle(AetheriaRtsIpcChannels.viewportFeedStop, (_event, subscriptionId: string) => {
    viewportFeedSubscriptions.get(subscriptionId)?.();
    viewportFeedSubscriptions.delete(subscriptionId);
  });
  ipcMain.handle(AetheriaRtsIpcChannels.setMoveVector, async (_event, request: AetheriaRuntimeSetMoveVectorRequest) =>
    getClient().setMoveVector(request));
  ipcMain.handle(AetheriaRtsIpcChannels.setTarget, async (_event, request: AetheriaRuntimeSetTargetRequest) =>
    getClient().setTarget(request));
  ipcMain.handle(AetheriaRtsIpcChannels.surfaceCatalog, () => getClient().surfaceCatalogDiagnostics());
  ipcMain.handle(AetheriaRtsIpcChannels.surfaceCatalogIndex, () => getClient().surfaceCatalogIndexDiagnostics());
  ipcMain.handle(AetheriaRtsIpcChannels.health, () => getHealth());
}

export type AetheriaRuntimeDaemonCommandSender = (
  commandId: string,
  issuedAtUtc: string,
  command: unknown[],
  context: CultMeshOperationContext,
) => Promise<void>;

export type AetheriaRuntimeViewportQueryExecutor<TResult> = (
  request: CultMeshViewportRequest,
  context: CultMeshQueryContext,
) => Promise<TResult>;

export type AetheriaRuntimeQueryExecutor<TParameters, TResult> = (
  request: TParameters,
  context: CultMeshQueryContext,
) => Promise<TResult>;

export type AetheriaRuntimeRtsQueryExecutors = {
  mapViewport: AetheriaRuntimeViewportQueryExecutor<ViewportResponse>;
  objectsViewport: AetheriaRuntimeViewportQueryExecutor<ObjectsViewportResponse>;
  gravityViewport: AetheriaRuntimeViewportQueryExecutor<GravityViewportResponse>;
  selectedObject: AetheriaRuntimeQueryExecutor<AetheriaRuntimeSelectedObjectRequest, SelectedObjectProjection>;
  inventory: AetheriaRuntimeQueryExecutor<AetheriaRuntimeSelectedObjectRequest, InventoryProjection>;
  daemonHealth: AetheriaRuntimeQueryExecutor<void, DaemonHealthProjection>;
  authorityStatus: AetheriaRuntimeQueryExecutor<void, AuthorityStatusProjection>;
  starbridgeSession: AetheriaRuntimeQueryExecutor<void, StarbridgeSessionProjection>;
};

export type AetheriaRuntimeRtsQueryWatchers = Partial<{
  mapViewport: CultMeshQueryWatcher<CultMeshViewportRequest, ViewportResponse>;
  objectsViewport: CultMeshQueryWatcher<CultMeshViewportRequest, ObjectsViewportResponse>;
  gravityViewport: CultMeshQueryWatcher<CultMeshViewportRequest, GravityViewportResponse>;
  selectedObject: CultMeshQueryWatcher<AetheriaRuntimeSelectedObjectRequest, SelectedObjectProjection>;
  inventory: CultMeshQueryWatcher<AetheriaRuntimeSelectedObjectRequest, InventoryProjection>;
  daemonHealth: CultMeshQueryWatcher<void, DaemonHealthProjection>;
  authorityStatus: CultMeshQueryWatcher<void, AuthorityStatusProjection>;
  starbridgeSession: CultMeshQueryWatcher<void, StarbridgeSessionProjection>;
}>;

export type AetheriaRuntimeRtsProjectionDiagnostic = CultMeshQuerySurfaceDiagnostic;

export type AetheriaRuntimeRtsLiveFeedDiagnostic = CultMeshLiveFeedDiagnostic;

export type AetheriaRuntimeRtsSurfaceCatalogDiagnostic = CultMeshSurfaceCatalogDiagnostic;

export type AetheriaRuntimeRtsOperationHandles = ReturnType<typeof createAetheriaRuntimeRtsOperationHandles>;

export type AetheriaRuntimeRtsDocuments = ReturnType<typeof createAetheriaRuntimeRtsDocuments>;

export type AetheriaRuntimeRtsStatePointers = AetheriaRuntimeRtsDocuments;

export type AetheriaRuntimeRtsDocumentResolvers = Partial<{
  daemonFrame: (context: CultMeshQueryContext) => Promise<unknown>;
  daemonHealth: (context: CultMeshQueryContext) => Promise<unknown>;
  authorityPolicy: (context: CultMeshQueryContext) => Promise<unknown>;
  starbridgeSession: (context: CultMeshQueryContext) => Promise<unknown>;
}>;

export type AetheriaRuntimeRtsStatePointerResolvers = AetheriaRuntimeRtsDocumentResolvers;

export const AetheriaRuntimeRtsProjectionSources = {
  daemonFrame: CultMesh.projectionSource("daemon:aetheria.frame.latest.v1", {
    schemaId: AetheriaRtsSchemas.daemonFrame,
    description: "latest daemon frame"
  }),
  daemonHealth: CultMesh.projectionSource("daemon:aetheria.health.latest.v1", {
    schemaId: AetheriaRtsSchemas.daemonHealth,
    description: "latest daemon health"
  }),
  authorityPolicy: CultMesh.projectionSource("daemon:aetheria.authority.policy.latest.v1", {
    schemaId: AetheriaRtsSchemas.verseAuthorityPolicy,
    description: "latest Verse authority policy"
  }),
  starbridgeSession: CultMesh.projectionSource("daemon:aetheria.starbridge.session.latest.v1", {
    schemaId: AetheriaRtsSchemas.starbridgeSessionSummary,
    description: "latest Starbridge session summary"
  })
} as const;

export function createAetheriaRuntimeRtsDocuments(
  routeHint: CultMeshRouteHint = CultMesh.routeHint(),
  resolvers: AetheriaRuntimeRtsDocumentResolvers = {},
) {
  return {
    daemonFrame: CultMesh.document(
      AetheriaRuntimeRtsProjectionSources.daemonFrame.sourceId,
      { schemaId: AetheriaRtsSchemas.daemonFrame },
      async (context) => resolvers.daemonFrame?.(context),
      {
        routeHint,
        sources: [AetheriaRuntimeRtsProjectionSources.daemonFrame],
      },
    ),
    daemonHealth: CultMesh.document(
      AetheriaRuntimeRtsProjectionSources.daemonHealth.sourceId,
      { schemaId: AetheriaRtsSchemas.daemonHealth },
      async (context) => resolvers.daemonHealth?.(context),
      {
        routeHint,
        sources: [AetheriaRuntimeRtsProjectionSources.daemonHealth],
      },
    ),
    authorityPolicy: CultMesh.document(
      AetheriaRuntimeRtsProjectionSources.authorityPolicy.sourceId,
      { schemaId: AetheriaRtsSchemas.verseAuthorityPolicy },
      async (context) => resolvers.authorityPolicy?.(context),
      {
        routeHint,
        sources: [AetheriaRuntimeRtsProjectionSources.authorityPolicy],
      },
    ),
    starbridgeSession: CultMesh.document(
      AetheriaRuntimeRtsProjectionSources.starbridgeSession.sourceId,
      { schemaId: AetheriaRtsSchemas.starbridgeSessionSummary },
      async (context) => resolvers.starbridgeSession?.(context),
      {
        routeHint,
        sources: [AetheriaRuntimeRtsProjectionSources.starbridgeSession],
      },
    ),
  } as const;
}

export const createAetheriaRuntimeRtsStatePointers = createAetheriaRuntimeRtsDocuments;

export function createAetheriaRuntimeRtsQueryHandles(
  executors: AetheriaRuntimeRtsQueryExecutors,
  routeHint: CultMeshRouteHint = CultMesh.routeHint(),
  watchers: AetheriaRuntimeRtsQueryWatchers = {},
) {
  return {
    mapViewport: CultMesh.projectionRecipe<CultMeshViewportRequest, ViewportResponse>(
      AetheriaRtsSchemas.rtsViewport,
      [AetheriaRuntimeRtsProjectionSources.daemonFrame],
      executors.mapViewport,
      { routeHint, watchProjection: watchers.mapViewport },
    ).asQuerySurface(),
    objectsViewport: CultMesh.projectionRecipe<CultMeshViewportRequest, ObjectsViewportResponse>(
      AetheriaRtsSchemas.objectsViewport,
      [AetheriaRuntimeRtsProjectionSources.daemonFrame],
      executors.objectsViewport,
      { routeHint, watchProjection: watchers.objectsViewport },
    ).asQuerySurface(),
    gravityViewport: CultMesh.projectionRecipe<CultMeshViewportRequest, GravityViewportResponse>(
      AetheriaRtsSchemas.gravityViewport,
      [AetheriaRuntimeRtsProjectionSources.daemonFrame],
      executors.gravityViewport,
      { routeHint, watchProjection: watchers.gravityViewport },
    ).asQuerySurface(),
    selectedObject: CultMesh.projectionRecipe<AetheriaRuntimeSelectedObjectRequest, SelectedObjectProjection>(
      AetheriaRtsSchemas.selectedObject,
      [AetheriaRuntimeRtsProjectionSources.daemonFrame],
      executors.selectedObject,
      { routeHint, watchProjection: watchers.selectedObject },
    ).asQuerySurface(),
    inventory: CultMesh.projectionRecipe<AetheriaRuntimeSelectedObjectRequest, InventoryProjection>(
      AetheriaRtsSchemas.inventory,
      [AetheriaRuntimeRtsProjectionSources.daemonFrame],
      executors.inventory,
      { routeHint, watchProjection: watchers.inventory },
    ).asQuerySurface(),
    daemonHealth: CultMesh.projectionRecipe<void, DaemonHealthProjection>(
      AetheriaRtsSchemas.daemonHealth,
      [AetheriaRuntimeRtsProjectionSources.daemonHealth],
      executors.daemonHealth,
      { routeHint, watchProjection: watchers.daemonHealth },
    ).asQuerySurface(),
    authorityStatus: CultMesh.projectionRecipe<void, AuthorityStatusProjection>(
      AetheriaRtsSchemas.verseAuthorityPolicy,
      [AetheriaRuntimeRtsProjectionSources.authorityPolicy],
      executors.authorityStatus,
      { routeHint, watchProjection: watchers.authorityStatus },
    ).asQuerySurface(),
    starbridgeSession: CultMesh.projectionRecipe<void, StarbridgeSessionProjection>(
      AetheriaRtsSchemas.starbridgeSessionSummary,
      [AetheriaRuntimeRtsProjectionSources.starbridgeSession],
      executors.starbridgeSession,
      { routeHint, watchProjection: watchers.starbridgeSession },
    ).asQuerySurface(),
  } as const;
}

export function describeAetheriaRuntimeRtsQueryHandles(
  handles: ReturnType<typeof createAetheriaRuntimeRtsQueryHandles>,
) {
  return {
    mapViewport: describeAetheriaRuntimeRtsQuerySurface(handles.mapViewport),
    objectsViewport: describeAetheriaRuntimeRtsQuerySurface(handles.objectsViewport),
    gravityViewport: describeAetheriaRuntimeRtsQuerySurface(handles.gravityViewport),
    selectedObject: describeAetheriaRuntimeRtsQuerySurface(handles.selectedObject),
    inventory: describeAetheriaRuntimeRtsQuerySurface(handles.inventory),
    daemonHealth: describeAetheriaRuntimeRtsQuerySurface(handles.daemonHealth),
    authorityStatus: describeAetheriaRuntimeRtsQuerySurface(handles.authorityStatus),
    starbridgeSession: describeAetheriaRuntimeRtsQuerySurface(handles.starbridgeSession),
  } as const;
}

export function describeAetheriaRuntimeRtsSurfaceCatalog(
  handles: ReturnType<typeof createAetheriaRuntimeRtsQueryHandles>,
  operations?: AetheriaRuntimeRtsOperationHandles,
  documents: AetheriaRuntimeRtsDocuments = createAetheriaRuntimeRtsDocuments(),
): AetheriaRuntimeRtsSurfaceCatalogDiagnostic {
  return CultMesh.describeSurfaceCatalog(
    "gamecult.aetheria.rts.surfaces.v1",
    [
      CultMesh.surfaceDiagnostic("state-pointer", documents.daemonFrame.documentId, {
        routeHint: documents.daemonFrame.routeHint,
        sources: documents.daemonFrame.sources,
      }),
      CultMesh.surfaceDiagnostic("state-pointer", documents.daemonHealth.documentId, {
        routeHint: documents.daemonHealth.routeHint,
        sources: documents.daemonHealth.sources,
      }),
      CultMesh.surfaceDiagnostic("state-pointer", documents.authorityPolicy.documentId, {
        routeHint: documents.authorityPolicy.routeHint,
        sources: documents.authorityPolicy.sources,
      }),
      CultMesh.surfaceDiagnostic("state-pointer", documents.starbridgeSession.documentId, {
        routeHint: documents.starbridgeSession.routeHint,
        sources: documents.starbridgeSession.sources,
      }),
      CultMesh.describeSurface(handles.mapViewport),
      CultMesh.describeSurface(handles.objectsViewport),
      CultMesh.describeSurface(handles.gravityViewport),
      CultMesh.describeSurface(handles.selectedObject),
      CultMesh.describeSurface(handles.inventory),
      CultMesh.describeSurface(handles.daemonHealth),
      CultMesh.describeSurface(handles.authorityStatus),
      CultMesh.describeSurface(handles.starbridgeSession),
      ...(operations
        ? [
            CultMesh.describeSurface(operations.setMoveVector),
            CultMesh.describeSurface(operations.setTarget),
          ]
        : []),
    ],
  );
}

function describeAetheriaRuntimeRtsQuerySurface(surface: {
  queryId: string;
  routeHint: CultMeshRouteHint;
  sources: readonly CultMeshProjectionSource[];
}): AetheriaRuntimeRtsProjectionDiagnostic {
  return CultMesh.describeQuerySurface(surface);
}

export function describeAetheriaRuntimeRtsLiveFeedSurface(surface: {
  feedId: string;
  routeHint: CultMeshRouteHint;
  sources: readonly CultMeshProjectionSource[];
}): AetheriaRuntimeRtsLiveFeedDiagnostic {
  return CultMesh.describeLiveFeed(surface);
}

export function createAetheriaRuntimeRtsOperationHandles(
  sendCommand: AetheriaRuntimeDaemonCommandSender,
  createCommandId: () => string = createDefaultCommandId,
) {
  return {
    setMoveVector: CultMesh.operation<AetheriaRuntimeSetMoveVectorRequest, AetheriaRuntimeDaemonCommandReceipt>(
      "gamecult.aetheria.pilot.set_move_vector.v1",
      async (request, context) => {
        const commandId = context.idempotencyKey ?? createCommandId();
        const issuedAtUtc = new Date().toISOString();
        await sendCommand(
          commandId,
          issuedAtUtc,
          encodeSetMoveVectorCommand(commandId, issuedAtUtc, context.runtimeId, request),
          context,
        );
        return {
          commandId,
          ...CultMesh.operationReceipt("gamecult.aetheria.pilot.set_move_vector.v1", true, { route: context.routeHint }),
        };
      },
    ),
    setTarget: CultMesh.operation<AetheriaRuntimeSetTargetRequest, AetheriaRuntimeDaemonCommandReceipt>(
      "gamecult.aetheria.pilot.set_target.v1",
      async (request, context) => {
        const commandId = context.idempotencyKey ?? createCommandId();
        const issuedAtUtc = new Date().toISOString();
        await sendCommand(
          commandId,
          issuedAtUtc,
          encodeSetTargetCommand(commandId, issuedAtUtc, context.runtimeId, request),
          context,
        );
        return {
          commandId,
          ...CultMesh.operationReceipt("gamecult.aetheria.pilot.set_target.v1", true, { route: context.routeHint }),
        };
      },
    ),
  } as const;
}

export type AetheriaRuntimeRtsVerseFacade = ReturnType<typeof createAetheriaRuntimeRtsVerseFacade>;

export function createAetheriaRuntimeRtsVerseFacade(
  queryVerse: CultMeshVerseContext,
  commandVerse: CultMeshVerseContext,
  queries: ReturnType<typeof createAetheriaRuntimeRtsQueryHandles>,
  operations: AetheriaRuntimeRtsOperationHandles,
  documents: AetheriaRuntimeRtsDocuments = createAetheriaRuntimeRtsDocuments(),
) {
  const mapViewport = CultMesh.bindQuery(queryVerse, queries.mapViewport);
  const objectsViewport = CultMesh.bindQuery(queryVerse, queries.objectsViewport);
  const gravityViewport = CultMesh.bindQuery(queryVerse, queries.gravityViewport);
  const selectedObject = CultMesh.bindQuery(queryVerse, queries.selectedObject);
  const inventory = CultMesh.bindQuery(queryVerse, queries.inventory);
  const daemonHealth = CultMesh.bindQuery(queryVerse, queries.daemonHealth);
  const authorityStatus = CultMesh.bindQuery(queryVerse, queries.authorityStatus);
  const starbridgeSession = CultMesh.bindQuery(queryVerse, queries.starbridgeSession);
  const daemonFrameDocument = CultMesh.bindDocument(queryVerse, documents.daemonFrame);
  const daemonHealthDocument = CultMesh.bindDocument(queryVerse, documents.daemonHealth);
  const authorityPolicyDocument = CultMesh.bindDocument(queryVerse, documents.authorityPolicy);
  const starbridgeSessionDocument = CultMesh.bindDocument(queryVerse, documents.starbridgeSession);
  const setMoveVector = CultMesh.bindOperation(commandVerse, operations.setMoveVector);
  const setTarget = CultMesh.bindOperation(commandVerse, operations.setTarget);

  return {
    zone: (_zoneId = "current") => ({
      viewport: {
        within: (request: CultMeshViewportRequest) =>
          mapViewport.execute(request),
        watch: (
          request: CultMeshViewportRequest,
          callback: (value: ViewportResponse) => void,
        ) => mapViewport.watch(request, callback),
      },
      objects: {
        visibleWithin: (request: CultMeshViewportRequest) =>
          objectsViewport.execute(request),
        watchVisibleWithin: (
          request: CultMeshViewportRequest,
          callback: (value: ObjectsViewportResponse) => void,
        ) => objectsViewport.watch(request, callback),
      },
      gravity: {
        within: (request: CultMeshViewportRequest) =>
          gravityViewport.execute(request),
        watchWithin: (
          request: CultMeshViewportRequest,
          callback: (value: GravityViewportResponse) => void,
        ) => gravityViewport.watch(request, callback),
      },
    }),
    entity: (entityKey: string) => ({
      pilot: {
        move: (
          direction: { readonly x: number; readonly y: number },
          options: { scalar?: number; observedFrameId?: number; commandId?: string } = {},
        ) => setMoveVector.invoke({
          actorEntityKey: entityKey,
          directionX: direction.x,
          directionY: direction.y,
          scalar: options.scalar ?? 1,
          observedFrameId: options.observedFrameId,
        }, { idempotencyKey: options.commandId }),
        target: (
          targetEntityKey: string,
          options: { observedFrameId?: number; commandId?: string } = {},
        ) => setTarget.invoke({
          actorEntityKey: entityKey,
          targetEntityKey,
          observedFrameId: options.observedFrameId,
        }, { idempotencyKey: options.commandId }),
      },
    }),
    selectedObject: (entityIndex: number) =>
      selectedObject.execute({ entityIndex }),
    inventory: (entityIndex: number) =>
      inventory.execute({ entityIndex }),
    daemon: {
      state: {
        frame: () => daemonFrameDocument.latest(),
        health: () => daemonHealthDocument.latest(),
        authorityPolicy: () => authorityPolicyDocument.latest(),
        starbridgeSession: () => starbridgeSessionDocument.latest(),
      },
      health: () => daemonHealth.execute(undefined),
      authorityStatus: () => authorityStatus.execute(undefined),
      starbridgeSession: () => starbridgeSession.execute(undefined),
    },
  } as const;
}

export function encodeSetMoveVectorCommand(
  commandId: string,
  issuedAtUtc: string,
  runtimeId: string,
  request: AetheriaRuntimeSetMoveVectorRequest,
): unknown[] {
  const command = createBaseCommand(commandId, issuedAtUtc, runtimeId, request.actorEntityKey, request.observedFrameId);
  command[aetheriaRuntimeDaemonCommandDocumentSlots.kind] = AetheriaRuntimeDaemonCommandKinds.setMoveVector;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.directionX] = request.directionX;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.directionY] = request.directionY;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.scalarValue] = Math.min(1, Math.max(0, request.scalar));
  return command;
}

export function encodeSetTargetCommand(
  commandId: string,
  issuedAtUtc: string,
  runtimeId: string,
  request: AetheriaRuntimeSetTargetRequest,
): unknown[] {
  const command = createBaseCommand(commandId, issuedAtUtc, runtimeId, request.actorEntityKey, request.observedFrameId);
  command[aetheriaRuntimeDaemonCommandDocumentSlots.kind] = AetheriaRuntimeDaemonCommandKinds.setTarget;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.targetEntityKey] = request.targetEntityKey;
  return command;
}

function createBaseCommand(
  commandId: string,
  issuedAtUtc: string,
  runtimeId: string,
  actorEntityKey: string,
  observedFrameId?: number,
): unknown[] {
  const command = new Array<unknown>(Object.keys(aetheriaRuntimeDaemonCommandDocumentSlots).length).fill(null);
  command[aetheriaRuntimeDaemonCommandDocumentSlots.schema] = AetheriaRtsSchemas.daemonCommand;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.commandId] = commandId;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.clientId] = runtimeId;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.issuedAtUtc] = issuedAtUtc;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.sessionId] = "local";
  command[aetheriaRuntimeDaemonCommandDocumentSlots.observedFrameId] = observedFrameId ?? -1;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.kind] = 0;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.actorEntityKey] = actorEntityKey;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.targetEntityKey] = "";
  command[aetheriaRuntimeDaemonCommandDocumentSlots.targetZoneIndex] = -1;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.equipmentIndex] = -1;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.behaviorIndex] = -1;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.weaponGroup] = -1;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.positionX] = 0;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.positionY] = 0;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.positionZ] = 0;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.directionX] = 0;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.directionY] = 0;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.scalarValue] = 0;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.textValue] = "";
  command[aetheriaRuntimeDaemonCommandDocumentSlots.authorRuntimeId] = "";
  command[aetheriaRuntimeDaemonCommandDocumentSlots.subjectKey] = "";
  command[aetheriaRuntimeDaemonCommandDocumentSlots.claimKind] = "";
  return command;
}

function createDefaultCommandId(): string {
  const cryptoApi = globalThis.crypto as { randomUUID?: () => string } | undefined;
  return cryptoApi?.randomUUID?.() ?? `command-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
}
