import type { CultMeshViewportRequest } from "cultmesh-ts";

export {
  AetheriaRtsIpcChannels,
  AetheriaRtsSchemas,
  AetheriaRuntimeDaemonCommandKinds,
  aetheriaRuntimeEveCommandDocumentSlots,
  createAetheriaRuntimeGameDocuments,
  createAetheriaRuntimeGameOperationHandles,
  createAetheriaRuntimeGameQueryHandles,
  createAetheriaRuntimeGameStatePointers,
  createAetheriaRuntimeGameVerseHandles,
  describeAetheriaRuntimeGameLiveFeedSurface,
  describeAetheriaRuntimeGameQueryHandles,
  describeAetheriaRuntimeGameSurfaceCatalog,
} from "./aetheria-rts-generated-bindings.js";

export type {
  AetheriaRuntimeDaemonCommandReceipt,
  AetheriaRuntimeGameLiveFeedDiagnostic,
  AetheriaRuntimeGameDocumentResolvers,
  AetheriaRuntimeGameDocuments,
  AetheriaRuntimeGameOperationHandles,
  AetheriaRuntimeGameQueryDiagnostic,
  AetheriaRuntimeGameStatePointerResolvers,
  AetheriaRuntimeGameStatePointers,
  AetheriaRuntimeGameSurfaceCatalogDiagnostic,
  AetheriaRuntimeGameVerseHandles,
  AetheriaRuntimeSelectedObjectRequest as SelectedObjectRequest,
  AetheriaRuntimeSetMoveVectorRequest as RtsSetMoveVectorRequest,
  AetheriaRuntimeSetTargetRequest as RtsSetTargetRequest,
  AetheriaRuntimeViewportFeedRequest,
  AetheriaRuntimeViewportFeedSnapshot,
  AssetManifestEntry,
  AssetManifestDocument,
  AssetRef,
  AuthorityRuleDocument,
  AuthorityStatusDocument,
  BodyView,
  DaemonHealthDocument,
  EntityStatus,
  GravityInfluence,
  GravityViewportResponse,
  InventoryItem,
  InventoryDocument,
  ObjectsViewportResponse,
  RenderSplatsViewportResponse,
  SelectedObjectDocument,
  StarbridgeBaseStatusDocument,
  StarbridgeRuntimeRoleDocument,
  StarbridgeSessionDocument,
  StarbridgeStationStockItemDocument,
  StarbridgeWaveForecastDocument,
  ViewObject,
  ViewportResponse,
} from "./aetheria-rts-generated-bindings.js";

export type ViewportRequest = CultMeshViewportRequest;
