// <auto-generated />
// Slot numbers, schema id, and enum values come from AetheriaRuntimeDaemonDocuments.cs.
// Semantic operation helpers are deliberately small and covered by the C# <-> TypeScript wire witness.

export const AetheriaDaemonCommandSchema = "gamecult.aetheria.daemon_command.v1" as const;

export const AetheriaRuntimeDaemonCommandKinds = {
  none: 0,
  ping: 1,
  setTarget: 2,
  clearTarget: 3,
  targetNearest: 4,
  targetNext: 5,
  targetPrevious: 6,
  targetReticle: 7,
  setMoveVector: 8,
  setLookDirection: 9,
  setTractorPower: 10,
  fireWeaponGroup: 11,
  setWeaponGroupActive: 12,
  setWeaponGroupMembership: 13,
  setBehaviorActive: 14,
  activateConsumable: 15,
  sensorPing: 16,
  setItemEnabled: 17,
  setItemOverrideShutdown: 18,
  setThermotoggleTargetTemperature: 19,
  pickUpLoot: 20,
  restoreLoadout: 21,
  dock: 22,
  dockNearest: 23,
  undock: 24,
  interact: 25,
  setDockedCurrentShip: 26,
  towToStation: 27,
  enterWormhole: 28,
  tradePurchase: 29,
  transferCargoItem: 30,
  equipItem: 31,
  storeItem: 32,
  toggleHullConductivity: 33,
  setEntityName: 34,
  destroyEntity: 35,
  setOverrideShutdown: 36,
  setHeatsinksEnabled: 37,
  setShutdownPerformance: 38,
  toggleShieldEnabled: 39,
  issueAgentTask: 40,
  cancelAgentTask: 41,
  setSimulationRate: 42,
  advanceSimulationStep: 43,
  tradeSale: 44,
} as const;

export const aetheriaRuntimeDaemonCommandDocumentSlots = {
  schema: 0, // string
  commandId: 1, // string
  clientId: 2, // string
  issuedAtUtc: 3, // string
  sessionId: 4, // string
  observedFrameId: 5, // long
  kind: 6, // AetheriaRuntimeDaemonCommandKinds
  actorEntityKey: 7, // string
  targetEntityKey: 8, // string
  targetZoneIndex: 9, // int
  equipmentIndex: 10, // int
  behaviorIndex: 11, // int
  weaponGroup: 12, // int
  positionX: 13, // double
  positionY: 14, // double
  positionZ: 15, // double
  directionX: 16, // double
  directionY: 17, // double
  scalarValue: 18, // double
  textValue: 19, // string
  cargoTransfer: 21, // AetheriaRuntimeCargoTransferCommand
  tradePurchase: 22, // AetheriaRuntimeTradePurchaseCommand
  lootPickup: 23, // AetheriaRuntimeLootPickupCommand
  loadoutRestore: 24, // AetheriaRuntimeLoadoutRestoreCommand
  equipmentTransfer: 25, // AetheriaRuntimeEquipmentTransferCommand
  storeItem: 26, // AetheriaRuntimeStoreItemCommand
  authorRuntimeId: 27, // string
  subjectKey: 28, // string
  claimKind: 29, // string
  agentTask: 30, // AetheriaRuntimeAgentTaskCommand
  tradeSale: 31, // AetheriaRuntimeTradeSaleCommand
} as const;

export type AetheriaRuntimeSetMoveVectorRequest = {
  actorEntityKey: string;
  directionX: number;
  directionY: number;
  scalar: number;
  observedFrameId?: number;
};

export type AetheriaRuntimeSetTargetRequest = {
  actorEntityKey: string;
  targetEntityKey: string;
  observedFrameId?: number;
};

export function encodeSetMoveVectorCommand(
  commandId: string,
  issuedAtUtc: string,
  runtimeId: string,
  request: AetheriaRuntimeSetMoveVectorRequest,
): unknown[] {
  const command = createBaseCommand(commandId, issuedAtUtc, runtimeId, request.actorEntityKey, request.observedFrameId);
  command[aetheriaRuntimeDaemonCommandDocumentSlots.kind] = AetheriaRuntimeDaemonCommandKinds.setMoveVector;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.directionX] = request.directionX;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.directionY] = request.directionY;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.scalarValue] = Math.min(1, Math.max(0, request.scalar));
  command[aetheriaRuntimeDaemonCommandDocumentSlots.claimKind] = "movement";
  return command;
}

export function encodeSetTargetCommand(
  commandId: string,
  issuedAtUtc: string,
  runtimeId: string,
  request: AetheriaRuntimeSetTargetRequest,
): unknown[] {
  const command = createBaseCommand(commandId, issuedAtUtc, runtimeId, request.actorEntityKey, request.observedFrameId);
  command[aetheriaRuntimeDaemonCommandDocumentSlots.kind] = AetheriaRuntimeDaemonCommandKinds.setTarget;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.targetEntityKey] = request.targetEntityKey;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.claimKind] = "targeting";
  return command;
}

function createBaseCommand(
  commandId: string,
  issuedAtUtc: string,
  runtimeId: string,
  actorEntityKey: string,
  observedFrameId?: number,
): unknown[] {
  const command = new Array<unknown>(32).fill(null);
  command[aetheriaRuntimeDaemonCommandDocumentSlots.schema] = AetheriaDaemonCommandSchema;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.commandId] = commandId;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.clientId] = runtimeId;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.issuedAtUtc] = issuedAtUtc;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.sessionId] = "local";
  command[aetheriaRuntimeDaemonCommandDocumentSlots.observedFrameId] = observedFrameId ?? -1;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.kind] = AetheriaRuntimeDaemonCommandKinds.none;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.actorEntityKey] = actorEntityKey;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.targetEntityKey] = "";
  command[aetheriaRuntimeDaemonCommandDocumentSlots.targetZoneIndex] = -1;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.equipmentIndex] = -1;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.behaviorIndex] = -1;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.weaponGroup] = -1;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.positionX] = 0;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.positionY] = 0;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.positionZ] = 0;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.directionX] = 0;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.directionY] = 0;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.scalarValue] = 0;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.textValue] = "";
  command[aetheriaRuntimeDaemonCommandDocumentSlots.authorRuntimeId] = runtimeId;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.subjectKey] = actorEntityKey;
  command[aetheriaRuntimeDaemonCommandDocumentSlots.claimKind] = "";
  return command;
}
