<Project>
  <PropertyGroup>
    <CultLibRoot Condition="'$(CultLibRoot)' == ''">$(MSBuildThisFileDirectory)..\..\CultLib</CultLibRoot>
    <CultLibRevision>334e60f1928b4212a29dd8b0d19b2c099fe6365e</CultLibRevision>
    <CultLibUnityTree>f771db72619bf668dcb94a8ad00ac9c2e73a1435</CultLibUnityTree>
    <GitExe Condition="'$(GitExe)' == '' and Exists('$(ProgramW6432)\Git\cmd\git.exe')">$(ProgramW6432)\Git\cmd\git.exe</GitExe>
    <GitExe Condition="'$(GitExe)' == ''">git</GitExe>
    <EvePluginsRoot Condition="'$(EvePluginsRoot)' == ''">$(MSBuildThisFileDirectory)..\..\EvePlugins</EvePluginsRoot>
    <EveRoot Condition="'$(EveRoot)' == ''">$(MSBuildThisFileDirectory)..\..\Eve</EveRoot>
    <EveRevision>96839ad34c8d464ef622d8bbdd5d277e1ca9d825</EveRevision>
    <EveSurfaceTree>783e75a25659bd8c43bc4624803ff8a6c58bca03</EveSurfaceTree>
    <YmirRoot Condition="'$(YmirRoot)' == ''">$(MSBuildThisFileDirectory)..\..\Ymir</YmirRoot>
  </PropertyGroup>
</Project>
